Feature/setup routing
vanmarcke/ocr_projet5_blog pull request #21
Opened 2021-09-28 13:12 UTC by vanmarcke

Close issue [#7 & #8 ]

Add file required for routing
Setting up routing
Home routing 
Update navbar

Verification and Modification according to codacy

2021-09-29 11:08 UTC, antoinetrouve requested changes

2021-09-29 11:08 UTC, antoinetrouve commented on .gitignore
> +/src/controller/EmailProcessing.php
Pourquoi ce fichier php est dans le .gitignore ?

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
Une ligne vide de trop

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
ligne vide inutile

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
idem

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
idem

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
idem

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
idem

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
idem

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +
idem

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/homepage.twig
> +        {# CONTACT END ***************************************** #}
pas besoin du CONTACT END ici, si tu ne le fais pas avant pour les hobbies et autres includes...

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/port_folio.twig
>                                                  <span aria-hidden="true">&times;</span>
portfolio c'est un seul mot. Pas besoin de le séprarer par un  "_". Tu peux renommer ton fichier en `portfolio.twig`

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/template.twig
> +<head>
Peut-être voir pour faire un block `head`

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/template.twig
> +<body id="body">
Voir pour faire un block body

2021-09-29 11:08 UTC, antoinetrouve commented on public/view/template.twig
> +
ligne superflus

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +        }else{
il manque un espace après et avant le `{`.

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +
Ligne superflu

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +        if(empty($response) || is_null($response)){
Ils manques des espaces après et avant tes `{`

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +            if($data->success){
Suggestion pour la syntaxe :
```
if () {
} else { 
}
```

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +    $email = 'votre email ici';
Il y a moyen ici de créer un model, une classe Email.

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/HomepageController.php
> +
Ligne superflue

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/HomepageController.php
> +
Ca manque de commentaire PHP. Histoire de savoir ce que ca fait. regarde au niveau de la PHPDoc

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/HomepageController.php
> +
Lignes superflus

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/Router.php
> +class Router{
Il manque des commentaires.

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/Router.php
> +
Ligne superflue

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/Router.php
> +
Ligne superflus

2021-09-29 11:08 UTC, antoinetrouve commented on src/controller/TwigController.php
> +class TwigController{
Il manque des commentaires

2021-09-29 12:13 UTC, vanmarcke commented on .gitignore
> +/src/controller/EmailProcessing.php
Il contient le code secret recaptcha et ne doit pas être visbile publiquement . C'est pour cela que j'ai créé le fichier "EmailProcessingCopy.php" qui lui est visibible mais sans le code secret.

2021-09-29 12:18 UTC, vanmarcke commented on public/view/homepage.twig
> +        {# CONTACT END ***************************************** #}
Ligne supprimée

2021-09-29 12:19 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:20 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:20 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:20 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:20 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:21 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:21 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne vide supprimée

2021-09-29 12:22 UTC, vanmarcke commented on public/view/port_folio.twig
>                                                  <span aria-hidden="true">&times;</span>
renomé en "portfolio.twig"

2021-09-29 12:24 UTC, vanmarcke commented on public/view/template.twig
> +
ligne supprimée

2021-09-29 12:40 UTC, vanmarcke commented on src/controller/HomepageController.php
> +
Ligne supprimée

2021-09-29 12:40 UTC, vanmarcke commented on src/controller/HomepageController.php
> +
Ligne supprimée

2021-09-29 12:41 UTC, vanmarcke commented on src/controller/Router.php
> +
Ligne supprimée

2021-09-29 12:42 UTC, vanmarcke commented on public/view/homepage.twig
> +
Ligne supprimée

2021-09-29 12:43 UTC, vanmarcke commented on src/controller/EmailProcessingCopy.php
> +        }else{
Espace ajouté après et avant le {

2021-09-29 12:43 UTC, vanmarcke commented on src/controller/EmailProcessingCopy.php
> +
Ligne supprimée

2021-09-29 12:44 UTC, vanmarcke commented on src/controller/EmailProcessingCopy.php
> +        if(empty($response) || is_null($response)){
Espace ajouté après et avant le {

2021-09-29 12:45 UTC, vanmarcke commented on src/controller/EmailProcessingCopy.php
> +            if($data->success){
Correction faite

2021-09-29 12:46 UTC, vanmarcke commented on src/controller/Router.php
> +
Ligne supprimée

2021-09-29 13:28 UTC, vanmarcke commented on src/controller/HomepageController.php
> +
Commentaire ajouté

2021-09-29 13:36 UTC, vanmarcke commented on src/controller/Router.php
> +class Router{
Commentaire ajouté : 

/**
* Function run 
 *
 * @return void
 */

2021-09-29 13:48 UTC, vanmarcke commented on src/controller/TwigController.php
> +class TwigController{
Commentaire ajoutée

2021-09-29 14:25 UTC, vanmarcke commented on public/view/template.twig
> +<head>
Block head fait

2021-09-29 15:05 UTC, vanmarcke commented on public/view/template.twig
> +<body id="body">
Pouvons nous voir ce point lors de notre prochaine session de mentora

2021-09-29 15:06 UTC, vanmarcke commented on src/controller/EmailProcessingCopy.php
> +    $email = 'votre email ici';
Pouvons nous voir ce point lors de notre prochaine session de mentora

2021-09-30 07:12 UTC, antoinetrouve approved these changes

2021-09-30 07:12 UTC, antoinetrouve commented on src/controller/HomepageController.php
>  class HomepageController extends TwigController{
Il faut systématiquement des commentaires sur tes classes et tes fonctions.

2021-09-30 07:12 UTC, antoinetrouve commented on src/controller/Router.php
>  class Router{
Il faut systématiquement des commentaires sur tes classes et tes fonctions

2021-09-30 07:12 UTC, antoinetrouve commented on src/controller/TwigController.php
>  class TwigController{
Un petit commentaire sur la classe, ce serait bien je pense.

2021-09-30 07:12 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +        if(function_exists('curl_version')) {
il manque des espaces sur tes if.
`if (hfbvqfbbvl) { 
       lkjbjqbkmbfj
} else { 
      mqnvoifnoaizvhn
}`

2021-09-30 07:17 UTC, antoinetrouve commented
Peux tu regarder pour configurer ton projet afin que le merge ne soit pas possible si toutes les conversations d'une pull request ne soient pas marquées comme "resolved" ?  Je pense que l'option est disponible dans les paramétrages de ton projet (https://github.com/palantir/bulldozer/issues/124)

2021-09-30 07:17 UTC, vanmarcke commented on src/controller/EmailProcessingCopy.php
> +        if(function_exists('curl_version')) {
Espaces ajoutés

2021-09-30 08:21 UTC, vanmarcke commented on src/controller/TwigController.php
>  class TwigController{
Commentaire ajouté

2021-09-30 08:27 UTC, vanmarcke commented on src/controller/HomepageController.php
>  class HomepageController extends TwigController{
Commentaire ajouté

2021-09-30 08:33 UTC, vanmarcke commented on src/controller/Router.php
>  class Router{
Commentaire ajouté

2021-10-01 07:09 UTC, antoinetrouve commented on src/controller/EmailProcessingCopy.php
> +    $email = 'votre email ici';
Oui carrément.

2021-10-01 08:47 UTC, merged