Feature/database creation
vanmarcke/ocr_projet5_blog pull request #22
Opened 2021-10-01 10:39 UTC by vanmarcke

Issues [ #9 & #10 ]

Add of the 'projet5_blog.sql' file for creating the database.

Add of the 'config.php' file to define the information necessary for the connection.

Creation of the Model class to define the database connection parameters.

2021-10-04 08:06 UTC, antoinetrouve requested changes

2021-10-04 08:06 UTC, antoinetrouve commented on projet5_blog.sql
> +  `publish` enum('valid','waiting','refuse') COLLATE utf8mb4_bin NOT NULL DEFAULT 'waiting',
``publish` enum('validate','pending','refused') COLLATE utf8mb4_bin NOT NULL DEFAULT 'pending',`

2021-10-04 08:06 UTC, antoinetrouve commented on projet5_blog.sql
> +  `publish` enum('valid','waiting') COLLATE utf8mb4_bin NOT NULL DEFAULT 'waiting',
`publish` enum('validate','pending') COLLATE utf8mb4_bin NOT NULL DEFAULT 'pending',`

Un post ne peut pas être en état `refused` ?

2021-10-04 08:06 UTC, antoinetrouve commented on projet5_blog.sql
> +  `publish` enum('valid','waiting','refuse') COLLATE utf8mb4_bin NOT NULL DEFAULT 'waiting',
Tu peux ajouter un commentaire sur le champs histoire de voir toutes les valeurs attendus pour cette colonne en utilisant l'instruction `COMMENT`.

2021-10-04 08:06 UTC, antoinetrouve commented on projet5_blog.sql
> +  `rank` enum('admin','pending','registered') COLLATE utf8mb4_bin NOT NULL DEFAULT 'pending'
Idem pour les commentaires

2021-10-04 08:06 UTC, antoinetrouve commented on src/model/model.php
> +class Model
Tu peux appeller la classe d'une manière plus explicite. Ici ce n'est pas vraiment un model que tu essais de faire mais tu tentes une connexion. J'aurai d'avantage vu un service Database plutôt qu'un model.
exemple : `class DatabaseService` avec en constructeur les informations qu'ils te faut pour faire la connexion. et ensuite dans ta class une fonction 'connexion() { } qui exécute la connexion.

De manière générale, il ne faut pas mettre de logique dans ton constructeur (ou en tout cas le moins possible)

2021-10-04 09:41 UTC, vanmarcke commented on projet5_blog.sql
> +  `publish` enum('valid','waiting','refuse') COLLATE utf8mb4_bin NOT NULL DEFAULT 'waiting',
Modification faite

2021-10-04 09:45 UTC, vanmarcke commented on projet5_blog.sql
> +  `publish` enum('valid','waiting') COLLATE utf8mb4_bin NOT NULL DEFAULT 'waiting',
Non, c'est uniquement l'administrateur qui est autorisé à écrire un article. Il sera soit en attente 'brouillont', soit validé 'visible par les visiteurs'.

2021-10-04 09:46 UTC, vanmarcke commented on projet5_blog.sql
> +  `publish` enum('valid','waiting','refuse') COLLATE utf8mb4_bin NOT NULL DEFAULT 'waiting',
Commentaire ajouté

2021-10-04 09:46 UTC, vanmarcke commented on projet5_blog.sql
> +  `rank` enum('admin','pending','registered') COLLATE utf8mb4_bin NOT NULL DEFAULT 'pending'
Commentaire ajouté

2021-10-04 10:25 UTC, antoinetrouve commented
Je ne vois pas tes modifications. (les commentaires et les enums de ta base de données).
Egalement essais de déplacer ton fichier config.php et ton script de base de données dans le dossiers src/config/database/
- dbConnexion.php
- db_script.sql

2021-10-04 13:57 UTC, vanmarcke commented on src/model/model.php
> +class Model
Class renommée en DatabaseService 
A voir par la suite les possibilités d'ameliorer cette fonction.

2021-10-04 15:11 UTC, antoinetrouve requested changes

2021-10-04 15:11 UTC, antoinetrouve commented on src/model/DatabaseService.php
>  	protected $bdd;
En Programmation orientée objet, il faut toujours "typer" les variables. 
Qu'est ce que c'est $database ? un String, un int, un array ?

2021-10-04 15:11 UTC, antoinetrouve commented on src/model/DatabaseService.php
> +class DatabaseService
`DatabaseService` n'est pas un model mais un Service. Je ne pense pas que la classe doit se trouver dans le dossier src/model. Tu peux te renseigner pour connaître la distinction en développement entre un `controller`, un `model`, un `service` et un `repository`.

2021-10-04 15:11 UTC, antoinetrouve commented on src/model/DatabaseService.php
> +		return $this->bdd = $bdd;
Attention ! Il n' y a pas de return dans un constructeur. 
Tu dois déplacer tout le code  du `try catch` dans une fonction de ta classe. Cette fonction peut-être static. (Tu peux regarder le cours d'opencalssrooms sur la programmation orientée objet : https://openclassrooms.com/fr/courses/1665806-programmez-en-oriente-objet-en-php?status=published) et ici du coup tu n'auras plus besoin de ton constructeur.

- Dans ton constructeur tu set tous les éléments de ton tableau  `$database` (dbServer, dbName, dbUser....)  un à un Exemple : `$this->server = $database['dbServer']` (à faire également pour les autres variables de` $database`). Et je serais toi je splitterais mon tableau $database en plusieurs variables dans les paramètres de mon constructeurs pour être sûr que tous les éléments dont tu as besoins pour faire ta connexion sont bien présent)

```suggestion
public function __construct (string $serverName, string $dbName, string $dbUser ....) {
       $this->server = $serverName;
       $this->database = $dbName;
       ........
}
		
```

- Tu développes une fonction **créer la connexion** et qui **retourne une instance de cette connexion** ( `return $pdo`). En gros ton `try catch`

2021-10-04 16:06 UTC, vanmarcke commented on src/model/DatabaseService.php
> +class DatabaseService
Déplacé dans un nouveau dossier service

2021-10-04 16:20 UTC, vanmarcke commented on src/model/DatabaseService.php
>  	protected $bdd;
param (array $dataBase) ajouté

2021-10-05 12:15 UTC, antoinetrouve commented on src/model/DatabaseService.php
> +		return $this->bdd = $bdd;
Essais de faire au mieux.

2021-10-10 10:29 UTC, antoinetrouve approved these changes

2021-10-11 06:38 UTC, merged

2021-10-11 06:44 UTC, vanmarcke commented
Closure issue #9 and #10

2021-10-11 06:46 UTC, vanmarcke commented
Closure issue #9 and #10